// Word pages that have enough search intent to justify indexable standalone URLs.
// Includes the normal English word URLs Google has already discovered, so those
// crawls resolve to canonical indexable pages instead of noindex or redirects.
export const INDEXABLE_WORDS: string[] = [
  "able", "act", "acute", "add", "adopt", "adult", "after", "age", "agree", "ahead",
  "air", "alarm", "album", "alert", "alive", "allow", "alone", "alter", "among", "and",
  "anger", "angry", "angle", "any", "apple", "apply", "are", "arena", "argue", "arm",
  "armed", "array", "asset", "audio", "audit", "avoid", "award", "bad", "badly", "baker",
  "bank", "base", "basic", "bat", "beach", "beat", "bed", "been", "began", "begin",
  "begun", "being", "below", "bench", "big", "bill", "billy", "birth", "black", "blade",
  "blame", "blank", "blend", "blind", "block", "blood", "blue", "boat", "body", "book",
  "boost", "booth", "board", "born", "both", "bound", "box", "brain", "brand", "bread", "break",
  "breed", "brief", "bring", "broad", "broke", "brown", "build", "but", "buyer", "cable",
  "calif", "call", "calm", "cap", "car", "care", "case", "cash", "cast", "cat",
  "catch", "cause", "chain", "chase", "cheap", "chest", "child", "chose", "city", "civil",
  "class", "clean", "clear", "click", "close", "club", "coast", "coat", "copy", "cost",
  "could", "count", "court", "cover", "craft", "cream", "crime", "cross", "crowd", "crown",
  "curve", "cut", "cycle", "daily", "date", "dawn", "dead", "deal", "dear", "debt",
  "deep", "deer", "did", "dirt", "dog", "door", "draw", "drop", "drug", "drum",
  "dry", "dual", "duke", "dust", "duty", "ear", "earn", "east", "eat", "edge",
  "egg", "else", "end", "eye", "face", "fact", "fail", "fair", "fan", "farm",
  "fat", "feed", "feel", "fell", "felt", "few", "file", "fill", "film", "find",
  "fine", "firm", "fish", "fit", "fix", "flew", "fog", "foot", "for", "ford", "form",
  "fort", "fun", "gas", "get", "got", "guy", "had", "has", "her", "hit",
  "how", "key", "kid", "lab", "law", "leg", "lie", "lot", "man", "map",
  "mom", "net", "new", "nor", "now", "nut", "oil", "one", "our", "owl",
  "own", "pan", "pen", "pet", "pig", "pin", "pop", "pro", "ran", "rat",
  "red", "rid", "row", "rub", "sad", "saw", "see", "set", "she", "sir",
  "sit", "six", "sky", "son", "tap", "ten", "the", "tip", "too", "top",
  "toy", "try", "win", "yes",
];
