name = "wordgrid"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./out"

[[d1_databases]]
binding = "DB"
database_name = "wordgrid-challenges"
database_id = "6c8e4c19-aed9-4dc7-a801-cb51a2234af9"
