import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Word Grid vs Boggle: What's the Difference?",
  description:
    "Boggle was invented in 1972. Word grid games took the concept online. Here's how they compare — the rules, scoring, and what playing online actually changes.",
  alternates: { canonical: "/guides/word-grid-vs-boggle" },
  openGraph: {
    title: "Word Grid vs Boggle: What's the Difference?",
    description:
      "How online word grid games compare to classic Boggle — rules, scoring, platforms, and what's genuinely better online.",
  },
};

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "Word Grid vs Boggle: What's the Difference?",
  description:
    "Comparing online word grid games to classic Boggle — rules, scoring, platforms, and gameplay differences.",
  author: { "@type": "Organization", name: "WordGrid" },
  publisher: { "@type": "Organization", name: "WordGrid" },
  datePublished: "2026-06-20",
  dateModified: "2026-06-20",
  mainEntityOfPage: "https://wordgrid.games/guides/word-grid-vs-boggle/",
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Word Grid", item: "https://wordgrid.games/" },
    { "@type": "ListItem", position: 2, name: "Guides", item: "https://wordgrid.games/guides/" },
    { "@type": "ListItem", position: 3, name: "Word Grid vs Boggle" },
  ],
};

export default function WordGridVsBoggleGuide() {
  return (
    <main className="min-h-screen px-4 py-8">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <article className="max-w-2xl mx-auto">
        <header className="mb-8">
          <nav className="text-sm text-text-dim flex items-center gap-2 mb-4">
            <a href="/" className="hover:text-text">Home</a>
            <span>/</span>
            <a href="/guides/" className="hover:text-text">Guides</a>
          </nav>
          <h1 className="text-4xl font-bold mb-2">
            Word Grid vs Boggle: What&apos;s the Difference?
          </h1>
          <p className="text-text-muted">5 min read &middot; Updated June 2026</p>
        </header>

        <div className="space-y-6 text-text">
          {/* Intro */}
          <section>
            <p className="leading-relaxed">
              Boggle has been around since 1972. If you played it as a kid, you
              probably remember the rattle of dice in a plastic dome and
              arguing over whether &ldquo;QATS&rdquo; is a real word (it is,
              technically).
            </p>
            <p className="leading-relaxed mt-3">
              Word grid games — like the one you&apos;re looking at right now —
              take the same concept and put it in your browser. The DNA is
              identical. But enough small things have changed that it&apos;s
              worth laying out exactly how they compare.
            </p>
          </section>

          {/* TL;DR comparison table */}
          <section>
            <h2 className="text-2xl font-semibold text-primary mb-3">
              The Quick Comparison
            </h2>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-2 text-text-muted">Feature</th>
                  <th className="text-left py-2 text-text-muted">Classic Boggle</th>
                  <th className="text-left py-2 text-text-muted">WordGrid</th>
                </tr>
              </thead>
              <tbody>
                {[
                  ["Grid size", "4×4 (16 dice)", "4×4 (16 cells)"],
                  ["Dice", "Physical, shaken", "Generated by algorithm"],
                  ["Q handling", "Qu on one tile", "Qu on one tile"],
                  ["Min word length", "3 letters", "3 letters"],
                  ["Time limit", "3 minutes (sand timer)", "3 min, 5 min, or Zen"],
                  ["Dictionary", "Printed booklet", "~55,000 words, built-in"],
                  ["Scoring", "1-11 pts by length", "1-10+ pts by length"],
                  ["Setup time", "~30 sec (shake, settle)", "Instant"],
                  ["Players", "2+ in person", "Solo, daily challenge"],
                  ["Platform", "Board game", "Any browser, no install"],
                ].map(([feature, boggle, wg]) => (
                  <tr key={feature} className="border-b border-surface">
                    <td className="py-2 font-medium">{feature}</td>
                    <td className="py-2 text-text-muted">{boggle}</td>
                    <td className="py-2 text-text-muted">{wg}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          {/* Same rules */}
          <section>
            <h2 className="text-2xl font-semibold text-primary mb-3">
              What Hasn&apos;t Changed
            </h2>
            <p className="leading-relaxed mb-3">
              The core rules are essentially identical:
            </p>
            <ul className="space-y-2 ml-4">
              <li>
                <strong>Same grid.</strong> 4×4 letters, 16 cells. The layout
                Boggle has used for over 50 years.
              </li>
              <li>
                <strong>Same adjacency rules.</strong> Connect letters
                horizontally, vertically, or diagonally. No jumping across the
                board.
              </li>
              <li>
                <strong>Same Qu tile.</strong> Q appears as &ldquo;Qu&rdquo; —
                always has, in every version of Boggle ever made. This is a
                tradition, not an accident.
              </li>
              <li>
                <strong>Same minimum length.</strong> Three letters. No
                exceptions.
              </li>
              <li>
                <strong>Same fundamental scoring curve.</strong> Longer words
                are worth exponentially more. The exact point values vary
                slightly between versions, but the principle never changes.
              </li>
            </ul>
            <p className="leading-relaxed mt-3">
              If you know how to play Boggle, you already know how to play
              WordGrid. There&apos;s no learning curve.
            </p>
          </section>

          {/* What's different */}
          <section>
            <h2 className="text-2xl font-semibold text-primary mb-3">
              What&apos;s Genuinely Different
            </h2>

            <h3 className="font-semibold text-lg mb-2 mt-4">
              No dice, no arguments
            </h3>
            <p className="leading-relaxed">
              In physical Boggle, someone has to shake the dice, and then
              everyone argues about whether a letter is a P or an F because it
              landed sideways. Online, the grid is computer-generated. Every
              letter is perfectly readable. No setup, no cleanup, no lost dice
              under the couch.
            </p>

            <h3 className="font-semibold text-lg mb-2 mt-4">
              The Daily Challenge
            </h3>
            <p className="leading-relaxed">
              This is the biggest structural difference. In physical Boggle,
              every game is random — you and your friend get a board, play it,
              move on. WordGrid&apos;s Daily Challenge gives everyone in the
              world the exact same grid on the same day.
            </p>
            <p className="leading-relaxed mt-3">
              It&apos;s like Wordle&apos;s daily puzzle mechanic, applied to
              Boggle. You can compare your score with friends knowing you all
              faced the same letters. The grid is deterministic — generated
              from a seed based on the date — so it&apos;s always fair.
            </p>

            <h3 className="font-semibold text-lg mb-2 mt-4">
              Flexible time limits
            </h3>
            <p className="leading-relaxed">
              Classic Boggle uses a 3-minute sand timer. The problem with sand
              timers is that they&apos;re imprecise — one person&apos;s 3
              minutes isn&apos;t necessarily the same as another&apos;s.
              WordGrid uses an exact digital timer. You can also choose 5 minutes
              for a more relaxed pace, or Zen mode with no timer at all.
            </p>

            <h3 className="font-semibold text-lg mb-2 mt-4">
              Bigger dictionary
            </h3>
            <p className="leading-relaxed">
              The dictionary that ships with physical Boggle is a small booklet
              — maybe 20,000 words, depending on the edition. WordGrid uses a
              list of about 55,000 words. You&apos;ll run into fewer
              &ldquo;that&apos;s definitely a word!&rdquo; moments where the
              booklet disagrees with you.
            </p>
            <p className="leading-relaxed mt-3">
              That said, some words still won&apos;t be accepted. Obscure words,
              very recent slang, and technical jargon are excluded to keep the
              game fair. If you want to know if a specific word is valid, each
              word has its own definition page — for example, here&apos;s{" "}
              <a href="/words/quest/" className="text-primary hover:underline">QUEST</a>{" "}
              or{" "}
              <a href="/words/trail/" className="text-primary hover:underline">TRAIL</a>.
            </p>

            <h3 className="font-semibold text-lg mb-2 mt-4">
              You can play alone
            </h3>
            <p className="leading-relaxed">
              Boggle is technically a multiplayer game — you need at least one
              other person. WordGrid works perfectly as a solo game. There&apos;s
              no waiting for someone else to be available, no setting up a
              physical board.
            </p>
          </section>

          {/* Which should you play */}
          <section>
            <h2 className="text-2xl font-semibold text-primary mb-3">
              So Which Should You Play?
            </h2>
            <p className="leading-relaxed">
              Honestly? Both. They&apos;re the same game with different
              conveniences. Physical Boggle is great if you have people in the
              same room and want a tactile experience. Online word grid games
              are better if you want to play quickly, play alone, or play the
              same daily puzzle as friends across the world.
            </p>
            <p className="leading-relaxed mt-3">
              The skills transfer perfectly. Get good at one and you&apos;ll be
              good at the other.
            </p>
          </section>

          {/* CTA */}
          <div className="mt-8 p-6 bg-indigo-900/30 rounded-xl border border-indigo-800/50">
            <h2 className="text-xl font-semibold text-primary mb-2">
              Try It Yourself
            </h2>
            <p className="text-text mb-4">
              You&apos;ve read enough comparisons. Play a round and decide for
              yourself — it takes 3 minutes.
            </p>
            <div className="flex gap-3">
              <a
                href="/play"
                className="px-6 py-3 bg-primary hover:bg-primary-hover transition rounded-xl font-semibold"
              >
                Play a Free Game
              </a>
              <a
                href="/daily"
                className="px-6 py-3 bg-surface hover:bg-surface-hover transition rounded-xl font-semibold"
              >
                Today&apos;s Challenge
              </a>
            </div>
          </div>

          {/* Related */}
          <div className="mt-8 border-t border-border pt-6">
            <h2 className="text-lg font-semibold mb-3">Keep Reading</h2>
            <div className="space-y-3">
              <a href="/guides/boggle-rules-beginners/" className="block bg-surface/50 hover:bg-surface transition rounded-xl p-4">
                <div className="font-semibold text-primary">Boggle Rules: A Complete Beginner&apos;s Guide &rarr;</div>
                <div className="text-sm text-text-muted">New to the game entirely? Start here for the full rules walkthrough.</div>
              </a>
              <a href="/guides/word-grid-strategies/" className="block bg-surface/50 hover:bg-surface transition rounded-xl p-4">
                <div className="font-semibold text-primary">Word Grid Strategies: Score Higher Every Game &rarr;</div>
                <div className="text-sm text-text-muted">Scoring math, time management, and word family patterns.</div>
              </a>
              <a href="/guides/" className="block text-sm text-text-dim hover:text-text">
                Browse all guides &rarr;
              </a>
            </div>
          </div>
        </div>
      </article>
    </main>
  );
}
